# Generated by Django 5.2.1 on 2025-05-11 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Curd'), ('DS', 'Dahi'), ('CH', 'Cheese'), ('YH', 'Yogurt'), ('BT', 'Butter'), ('CM', 'Cream'), ('PW', 'Paneer Whey'), ('WH', 'Whey'), ('GH', 'Ghee'), ('ML', 'Milk'), ('IC', 'Ice Cream'), ('PN', 'Paneer')], max_length=2),
        ),
    ]
